# you may need to add to this list if containers need to have internet access
# AND talk to other containers.
x-no-proxy: &no-proxy localhost

x-proxy-common: &proxy-common
  HTTP_PROXY: ${HTTP_PROXY:-}
  http_proxy: ${http_proxy:-}
  HTTPS_PROXY: ${HTTPS_PROXY:-}
  https_proxy: ${https_proxy:-}
  NO_PROXY: *no-proxy
  no_proxy: *no-proxy

services:
  waveform-controller:
    build:
      context: ..
      dockerfile: waveform-controller/Dockerfile
      target: waveform_controller
      args:
        <<: *proxy-common
    # ideally we'd use docker secrets but it's not enabled currently
    env_file:
     - ../config/controller.env
    volumes:
      - ../waveform-export:/waveform-export
    restart: unless-stopped
  waveform-exporter:
    build:
      context: ..
      dockerfile: waveform-controller/Dockerfile
      target: waveform_exporter
      args:
        <<: *proxy-common
        # Set to 1 in integration tests so COVERAGE_PROCESS_START can collect data.
        # Default 0 keeps production/dev images free of the coverage package.
        INSTALL_COVERAGE: ${INSTALL_COVERAGE:-0}
    # ideally we'd use docker secrets but it's not enabled currently
    env_file:
      - ../config/exporter.env
    volumes:
      - ../waveform-export:/waveform-export
      # because we're launching through cron in the container, which starts
      # processes with a clean environment, also mount in the config file so
      # it can be read in by snakemake later
      - ../config/exporter.env:/config/exporter.env:ro
    restart: unless-stopped
  waveform-hasher:
    build:
      context: ../PIXL
      dockerfile: ./docker/pixl-python/Dockerfile
      target: hasher_api
      args:
        PIXL_PACKAGE_DIR: hasher
        <<: *proxy-common
    ports:
      # this is only here as a convenience for testing, we don't actually use it from the exporter
      - "127.0.0.1::8000"
    env_file:
      - ../config/hasher.env
    environment:
      <<: *proxy-common
    restart: unless-stopped
  waveform-monitoring:
    # This service exists as a partly temporary measure, covering a few different cases:
    #   * Until LGTM on the GAE can tell us disk free amount for /gae
    #   * Stats on HL7 bz2 files on disk. Arguably done better in Emap but
    #     I'm putting all the telemetry in one project for now.
    #   * Disk usage stats for the waveform processing (CSVs, parquets, etc). This will likely stay here.
    build:
      context: .
      dockerfile: monitoring/Dockerfile
      args:
        <<: *proxy-common
    env_file:
      - ../config/monitoring.env
    volumes:
      # we are assuming this FS layout to emap saved messages
      - ../../waveform-saved-messages:/waveform-saved-messages:ro
      - ../waveform-export:/waveform-export:ro
    restart: unless-stopped
