[project]
name = "waveform_controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas==2.2.3",
    #"pyarrow>=22.0",
    "pika>=1.3.2",
    "pre-commit>=4.5.0",
    "snakemake==9.14.5",
    "opentelemetry-distro==0.63b1",
    "opentelemetry-exporter-otlp-proto-http==1.42.0",
    # need to be compatible with PIXL, which currently pins 2.9.10 (arguably it shouldn't)
    "psycopg2-binary>=2.9.10",
    "requests==2.32.4",
    # trick for making a "relative" path, works inside or outside container image
    "core @ file:///${PROJECT_ROOT}/../PIXL/pixl_core",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
    "stablehash==0.3.0",
    "types-pika-ts",
    "types-psycopg2",
]

[project.scripts]
emap-extract-waveform = "controller:receiver"
emap-csv-pseudon = "pseudon.pseudon:psudon_cli"
emap-send-ftps = "exporter.ftps:do_upload_cli"

[tool.pytest.ini_options]
# Force temp dirs under the repo so Docker can mount them on macOS.
# The default under /private/var/folders seems to silently fail (gives you an empty directory)
addopts = "--basetemp=.pytest_tmp"

[tool.mypy]
ignore_missing_imports = true
# opentelemetry docs recommend this
namespace_packages = true
