import os
import sys
from datetime import datetime, timedelta, timezone
from snakemake.io import glob_wildcards
from exporter.ftps import do_upload
from locations import (
    WAVEFORM_EXPORT_BASE,
    WAVEFORM_ORIGINAL_CSV,
    WAVEFORM_ORIGINAL_PARQUET,
    WAVEFORM_SNAKEMAKE_LOGS,
    WAVEFORM_PSEUDONYMISED_PARQUET,
    WAVEFORM_FTPS_LOGS)
from pathlib import Path
from pseudon.hashing import do_hash
from pseudon.pseudon import csv_to_parquets



def get_file_age(file_path: Path) -> timedelta:
    # need to use UTC to avoid DST issues
    file_time_utc = datetime.fromtimestamp(file_path.stat().st_mtime, timezone.utc)
    now_utc = datetime.now(timezone.utc)
    return now_utc - file_time_utc

def hash_csn(csn: str) -> str:
    return do_hash("csn", csn)


# How long before we assume that no more data will be written to the file, and
# that we can process it.
# In production we may wish to use something in the order of hours.
# We may also wish to compare it to the latest modified time of *any* file,
# to be sure that the data hasn't just stopped coming in altogether. (would not
# protect against very out of order data though)
# Also note that snakemake can detect and re-run if the file is subsequently updated,
# so being very cautious here may not be necessary.
CSV_WAIT_TIME = timedelta(minutes=5)

# input_csvs = [f for f in WAVEFORM_ORIGINAL_CSV.glob("*.csv")
#               if get_file_age(f) > CSV_WAIT_TIME
#               ]


# Parse all CSVs using the basic file name pattern
FILE_STEM_PATTERN = "{date}.{csn}.{stream_id}.{units}"
FILE_STEM_PATTERN_HASHED = "{date}.{hashed_csn}.{stream_id}.{units}"
CSV_PATTERN = WAVEFORM_ORIGINAL_CSV / (FILE_STEM_PATTERN + ".csv")
all_wc = glob_wildcards(CSV_PATTERN)

# all_wc.date, all_wc.csn, all_wc.streamId, all_wc.units are parallel lists
# e.g. all_wc.csn[0] corresponds to all_wc.date[0], etc.

# Build reverse lookup using named wildcards
HASH_TO_CSN: dict[str, str] = {}
for csn in all_wc.csn:
    HASH_TO_CSN[hash_csn(csn)] = csn
# Apply all_wc to FILE_STEM_PATTERN_HASHED to generate the output stems
all_outputs = []
for date, csn, stream_id, units in zip(all_wc.date, all_wc.csn, all_wc.stream_id, all_wc.units):
    subs_dict = dict(
        date = date,
        csn = csn,
        hashed_csn = hash_csn(csn),
        stream_id = stream_id,
        units = units
    )
    if csn == '5f5c24f4' or hash_csn(csn) == '5f5c24f4':
        print("JES JES WTH")
    print(f"{subs_dict}")
    orig_file = Path(str(CSV_PATTERN).format(**subs_dict))
    if csn == 'unmatched_csn':
        print(f"Skipping file with unmatched CSN: {orig_file}")
        continue
    file_age = get_file_age(orig_file)
    if file_age < CSV_WAIT_TIME:
        print(f"Skipping file that's too new ({file_age=}): {orig_file}")
        continue
    final_stem = FILE_STEM_PATTERN_HASHED.format(**subs_dict)
    final_output_file = WAVEFORM_FTPS_LOGS / (final_stem + ".ftps.sent")
    all_outputs.append(final_output_file)


# for ic in input_csvs:
#     print(f"input CSV: {ic}")

for hash, csn in HASH_TO_CSN.items():
    print(f"HASH_TO_CSN PID={os.getpid()}: {hash} ({type(hash)}): {csn} ({type(csn)})")

# Derive the output parquet paths from them
# def csv_to_ftps_sentinel(csv_path):
#     return str(WAVEFORM_FTPS_LOGS / Path(csv_path).name.replace(".csv", ".ftps.sent"))

# all_outputs = [csv_to_ftps_sentinel(f) for f in input_csvs]

for oc in all_outputs:
    print(f"output CSV: {oc}")

# I don't use f-strings in the input/output patterns because the escapes get too confusing
rule all:
    input:
        all_outputs

def input_file_maker(wc):
    # lambda wc: WAVEFORM_ORIGINAL_CSV / f"{wc.date}.{HASH_TO_CSN[wc.hashed_csn]}.{wc.stream_id}.{wc.units}.csv"
    print(f"input_file_maker: {len(HASH_TO_CSN)} - {wc.hashed_csn} ({type(wc.hashed_csn)}) - {HASH_TO_CSN.get(wc.hashed_csn)} ({type(HASH_TO_CSN.get(wc.hashed_csn))}) ", file=sys.stderr)
    print(f"input_file_maker(pre) PID={os.getpid()} looking up {wc.hashed_csn} (={HASH_TO_CSN.get(wc.hashed_csn)}) in hash of length {len(HASH_TO_CSN)} entries", file=sys.stderr)
    print(f"input_file_maker(pre) hashkeys={HASH_TO_CSN.keys()}", file=sys.stderr)
    unhashed_csn = HASH_TO_CSN[wc.hashed_csn]
    print(f"input_file_maker(post) found {unhashed_csn}", file=sys.stderr)
    return WAVEFORM_ORIGINAL_CSV / f"{wc.date}.{unhashed_csn}.{wc.stream_id}.{wc.units}.csv"

rule csv_to_parquet:
    input:
        # WAVEFORM_ORIGINAL_CSV / (FILE_STEM_PATTERN + ".csv"),
        # when using input functions, snakemake doesn't do its normal templating, you have to do it, hence the f-string
        input_file_maker
    output:
        # WAVEFORM_ORIGINAL_PARQUET / (FILE_STEM_PATTERN + ".parquet"),
        WAVEFORM_PSEUDONYMISED_PARQUET / (FILE_STEM_PATTERN_HASHED + ".parquet")
    log:
        # these do not get uploaded as they may contain identifiers
        WAVEFORM_SNAKEMAKE_LOGS / (FILE_STEM_PATTERN_HASHED + ".log")
    run:
        csv_to_parquets(Path(input[0]))

rule send_ftps:
    input:
        WAVEFORM_PSEUDONYMISED_PARQUET / (FILE_STEM_PATTERN_HASHED + ".parquet")
    output:
        # sentinel file
        WAVEFORM_FTPS_LOGS / (FILE_STEM_PATTERN_HASHED + ".ftps.sent")
    log:
        WAVEFORM_FTPS_LOGS / (FILE_STEM_PATTERN_HASHED + ".ftps.log")
    run:
        do_upload(Path(input[0]))
