import json
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

from exporter.daily_summary import make_daily_hash_summary
from exporter.ftps import do_upload
from locations import (
    WAVEFORM_ORIGINAL_CSV,
    WAVEFORM_SNAKEMAKE_LOGS,
    WAVEFORM_PSEUDONYMISED_PARQUET,
    WAVEFORM_PSEUDONYMISED_EHR,
    WAVEFORM_FTPS_LOGS,
    HASH_LOOKUP_JSON,
    HASH_LOOKUP_JSON_REL,
    FILE_STEM_PATTERN,
    FILE_STEM_PATTERN_HASHED,
    EHR_STEM_PATTERN_HASHED,
    make_file_name,
)
from pseudon.pseudon import csv_to_parquets
from electronic_health_records.ehr import ehr_for_csv

from utils import config_bool, determine_eventual_outputs


# How long before we assume that no more data will be written to the file, and
# that we can process it.
# In production we may wish to use something in the order of hours.
# We may also wish to compare it to the latest modified time of *any* file,
# to be sure that the data hasn't just stopped coming in altogether. (would not
# protect against very out of order data though)
# Also note that snakemake can detect and re-run if the file is subsequently updated,
# so being very cautious here may not be necessary.
CSV_AGE_THRESHOLD_MINUTES = timedelta(minutes=float(config['CSV_AGE_THRESHOLD_MINUTES']))

# To prevent Snakemake picking up old files in production, we can set a flag to to only
# use files with a date prefix matching yesterday's date. Defaults to True
ONLY_USE_CSV_FROM_YESTERDAY = config_bool(config['ONLY_USE_CSV_FROM_YESTERDAY'])

# We can optionally select a single date to process or a regular expression to match multiple dates.
PROCESS_CSV_FROM_DATE = str(config['PROCESS_CSV_FROM_DATE'])

# The problem here is that snakemake works "backwards" in that you have to define which
# files you want to be produced, yet we don't know what output files we need until the
# input files (original CSVs) are present.
# Therefore, look at the input files and work out the eventual output files so they can
# be fed into snakemake.

all_outputs, hash_to_csn = determine_eventual_outputs(CSV_AGE_THRESHOLD_MINUTES, ONLY_USE_CSV_FROM_YESTERDAY, PROCESS_CSV_FROM_DATE)
ALL_FTPS_UPLOADED = [ao.get_ftps_uploaded_file() for ao in all_outputs]
ALL_DAILY_HASH_LOOKUPS = sorted({ao.get_daily_hash_lookup() for ao in all_outputs})
ALL_EHR_LOOKUPS = sorted({ao.get_ehr_lookup() for ao in all_outputs})

def configure_file_logging(log_file):
    import logging
    logging.basicConfig(
        filename=log_file,
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        force=True
    )
    print(f"Configured logging to use file {log_file}")
    logger = logging.getLogger(__name__)
    return logger


rule all:
    input:
        ftps_uploaded = ALL_FTPS_UPLOADED,
        daily_hash_lookups = ALL_DAILY_HASH_LOOKUPS,
        ehr_lookups = ALL_EHR_LOOKUPS

rule all_ftps_uploaded:
    input:
        ALL_FTPS_UPLOADED

rule all_daily_hash_lookups:
    input:
        ALL_DAILY_HASH_LOOKUPS

rule all_ehr_lookups:
    input:
        ALL_EHR_LOOKUPS

def input_file_maker(wc):
    unhashed_csn = hash_to_csn[wc.hashed_csn]
    # when using input functions, snakemake doesn't do its normal templating, you have to do it, hence the f-string
    subs_dict = dict(
        date=wc.date,
        csn=unhashed_csn,
        variable_id=wc.variable_id,
        channel_id=wc.channel_id,
        units=wc.units,
    )
    stem = make_file_name(FILE_STEM_PATTERN, subs_dict)
    return WAVEFORM_ORIGINAL_CSV / f"{stem}.csv"

rule csv_to_parquet:
    input:
        input_file_maker
    output:
        # Do not specify the original parquet as an output, even though it is,
        # because snakemake doesn't allow a different subset of wildcards to be used in each output file.
        # WAVEFORM_ORIGINAL_PARQUET / (FILE_STEM_PATTERN + ".parquet"),
        WAVEFORM_PSEUDONYMISED_PARQUET / (FILE_STEM_PATTERN_HASHED + ".parquet")
    log:
        # these do not get uploaded as they may contain identifiers
        WAVEFORM_SNAKEMAKE_LOGS / "csv_to_parquet" / (FILE_STEM_PATTERN_HASHED + ".log")
    run:
        logger = configure_file_logging(log[0])
        original_csn = hash_to_csn[wildcards.hashed_csn]
        logger.info("Running csv to parquets, csn %s -> %s", original_csn, wildcards.hashed_csn)
        csv_to_parquets(
            date_str=wildcards.date,
            original_csn=original_csn,
            hashed_csn=wildcards.hashed_csn,
            variable_id=wildcards.variable_id,
            channel_id=wildcards.channel_id,
            units=wildcards.units)


def pseudonymised_parquet_files_for_date(wc):
    return [ao.get_pseudonymised_parquet_path() for ao in all_outputs if ao.date == wc.date]


def pseudonymised_parquet_files_for_date_and_hashed_csn(wc):
    return [
        ao.get_pseudonymised_parquet_path()
        for ao in all_outputs
        if ao.date == wc.date and ao.hashed_csn == wc.hashed_csn
    ]


rule ehr_lookup:
    input:
        # As with daily_hash_lookup, we lie to Snakemake that the input is the pseudon
        # parquets for this csn/day, purely so this rule is tied into the dependency DAG
        # and reruns if the underlying data for this csn/day changes.
        pseudonymised_parquets = pseudonymised_parquet_files_for_date_and_hashed_csn
    output:
        WAVEFORM_PSEUDONYMISED_EHR / (EHR_STEM_PATTERN_HASHED + "_ehr.csv")
    log:
        WAVEFORM_SNAKEMAKE_LOGS / "ehr_lookup" / (EHR_STEM_PATTERN_HASHED + ".log")
    run:
        logger = configure_file_logging(log[0])
        original_csn = hash_to_csn[wildcards.hashed_csn]
        logger.info("Running EHR look up for csn %s. Hash -> %s", original_csn, wildcards.hashed_csn)
        ehr_for_csv(
            date_str=wildcards.date,
            original_csn=original_csn,
            hashed_csn=wildcards.hashed_csn)


rule daily_hash_lookup:
    input:
        # Because we don't declare the original parquets in the output of csv_to_parquet,
        # they are not present in the Snakemake dependency DAG. Therefore, we can't reference them
        # here either.
        # We lie to Snakemake that the input is the pseudon parquets, but then we use InputCsvFile
        # to determine the actual input file (the original parquets).
        pseudonymised_parquets = pseudonymised_parquet_files_for_date
    output:
        hash_lookup_json = HASH_LOOKUP_JSON
    log:
        WAVEFORM_SNAKEMAKE_LOGS / "daily_hash_lookup" / HASH_LOOKUP_JSON_REL.with_suffix(".log")
    run:
        logger = configure_file_logging(log[0])
        daily_files = [ao for ao in all_outputs if ao.date == wildcards.date]
        logger.info(
            f"Making daily hash lookup {output.hash_lookup_json} from {len(daily_files)} files: "
            f"{input.pseudonymised_parquets}"
        )
        make_daily_hash_summary(daily_files, output.hash_lookup_json)


rule send_ftps:
    input:
        WAVEFORM_PSEUDONYMISED_PARQUET / (FILE_STEM_PATTERN_HASHED + ".parquet")
    output:
        # sentinel file
        WAVEFORM_FTPS_LOGS / (FILE_STEM_PATTERN_HASHED + ".ftps.uploaded.json")
    log:
        WAVEFORM_FTPS_LOGS / (FILE_STEM_PATTERN_HASHED + ".ftps.log")
    run:
        start_perf = time.perf_counter()
        start_timestamp = datetime.now(timezone.utc).isoformat()
        logger = configure_file_logging(log[0])
        logger.info("Calling do_upload to upload file %s", input[0])
        do_upload(Path(input[0]))
        end_perf = time.perf_counter()
        end_timestamp = datetime.now(timezone.utc).isoformat()
        # now that we have success, create the sentinel file
        with open(output[0], "w") as fh:
            json.dump(
                {
                    "uploaded_file": str(input[0]),
                    "upload_time_secs": end_perf - start_perf,
                    "start_timestamp": start_timestamp,
                    "end_timestamp": end_timestamp,
                },
                fh,
                indent=0,
            )
