name: Run pytest

on: 
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Run pytest
    runs-on: ubuntu-latest
    env:
      PROJECT_ROOT: ${{ github.workspace }}/waveform-controller
    environment: hasher
    steps:
      - uses: actions/checkout@v5
        with:
          path: waveform-controller
      - name: Checkout PIXL dependency
        uses: actions/checkout@v5
        with:
          repository: SAFEHR-data/PIXL
          # this version requires some old versions of things, but we'll upgrade when we're ready
          ref: 4a0a8392e982ce15aa84f4fdec76d425f4acd754  # pragma: allowlist secret
          path: PIXL

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.12.5"
          python-version: "3.13"
          enable-cache: true

      - name: Make a venv
        working-directory: waveform-controller
        run: uv venv

      - name: Install with dependencies
        working-directory: waveform-controller
        run: uv pip install '.[dev]'

      - name: Prepare config env files for compose
        working-directory: waveform-controller
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_KEY_VAULT_NAME: ${{ secrets.AZURE_KEY_VAULT_NAME }}
          AZURE_KEY_VAULT_SECRET_NAME: ${{ vars.AZURE_KEY_VAULT_SECRET_NAME }}
        run: |
          mkdir -p ../config
          cp config.EXAMPLE/exporter.env.EXAMPLE ../config/exporter.env
          cp config.EXAMPLE/hasher.env.EXAMPLE ../config/hasher.env
          cp config.EXAMPLE/controller.env.EXAMPLE ../config/controller.env
          {
            echo ""
            echo "AZURE_CLIENT_ID=${AZURE_CLIENT_ID}"
            echo "AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}"
            echo "AZURE_TENANT_ID=${AZURE_TENANT_ID}"
            echo "AZURE_KEY_VAULT_NAME=${AZURE_KEY_VAULT_NAME}"
            echo "AZURE_KEY_VAULT_SECRET_NAME=${AZURE_KEY_VAULT_SECRET_NAME}"
          } >> ../config/hasher.env
          
          # exporter config can't be done here because test_snakemake_integration.py wires in its own config file

      - name: Run the tests
        working-directory: waveform-controller
        run: uv run pytest tests --cov=src --cov-report=term-missing --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          directory: waveform-controller
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
